.build_job: &job_build
  stage: build
  script:
     - apt-get update && apt-get -y dist-upgrade
     - ci-build-pkg
  artifacts:
    expire_in: 1 hour
    paths:
      - result/*
  tags:
    - docker
      
stages:
 - build
 - sign
 - deploy
 - staging
 - production

before_script:
  - unset http_proxy ; unset https_proxy
  - env | grep ^CI_

# we use YAML anchors to define same parameters for all builds
#
build_debian_jessie:
  image: buildpkg/debian:jessie
  <<: *job_build

build_debian_stretch:
  image: buildpkg/debian:stretch
  <<: *job_build

build_centos_7:
  image: buildpkg/centos:7
  <<: *job_build

sign:
  image: buildpkg/debian:stretch
  stage: sign
#  secret variables defined:
#    SIGN_USER: firstname.lastname@example.com
#    GPG_PRIVATE_KEY: `gpg --armor --export-secret-keys firstname.lastname@example.com`
  script:
    - ci-sign-pkg
  dependencies:
    - build_debian_jessie
    - build_debian_stretch
    - build_centos_7
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  tags:
    - docker

pages:
  image: buildpkg/debian:stretch
  stage: deploy
#  variables:
#    PAGES_DIR: public/ppa
  environment:
    name: PPA
    url: http://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}
  script:
    - ci-pages-ppa
    - ci-pages-home
    - ci-pages-tree
  dependencies:
    - sign
  artifacts:
    paths:
      - public
  tags:
    - docker 
  only:
    - master