---
stages:
 - build
 - sign
 - deploy

before_script:
  - unset http_proxy ; unset https_proxy
  - env | grep ^CI_

build_centos_7:
  image: buildpkg/centos:7
  stage: build
  script:
     - ci-build-pkg
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  tags:
    - docker

build_fedora_25:
  image: buildpkg/fedora:25
  stage: build
  script:
     - ci-build-pkg
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  tags:
    - docker


sign:
  image: buildpkg/debian:stretch
  stage: sign
#  variables:
#    SIGN_USER: firstname.lastname@example.com
#    GPG_PRIVATE_KEY:
  script:
    - ci-sign-pkg
  dependencies:
    - build_centos_7
    - build_fedora_25
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  tags:
    - docker


pages:
  image: buildpkg/debian:stretch
  stage: deploy
#  variables:
#    PAGES_DIR: public/ppa
  environment:
    name: PPA
    url: http://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}
  script:
    - ci-pages-ppa
    - ci-pages-home
    - ci-pages-tree
  dependencies:
    - sign
  artifacts:
    paths:
      - public
  tags:
    - docker 
  only:
    - master