---
stages:
  - build
  - test
  - upload
  
before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"
   
after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

# use vale software to asciidoc syntax
unit:asciidoc:
  stage: build
  image: jdkato/vale
  script:
    - vale README.asciidoc
    
build:debian:
  image: debian:jessie-slim
  stage: build
  script:
    - apt-get update && apt-get install asciidoctor -y
    - echo "Install build tools"
    - apt-get install build-essential
    - make html

build:centos:
  image: centos:latest
  stage: build
  script:
    - yum install -y epel-release
    - yum install -y asciidoctor
    - echo "Install build tools"
    - yum groupinstall "Development Tools" -y
    - make html

test1:
  stage: test
  script: 
    - echo "Do a test here"
    - echo "For example run a test suite"
   
test2:
  stage: test
  script: 
    - echo "Do another parallel test here"
    - echo "For example run a lint test"
